// ノード id の一意制約。
// 定義の一次資料は docs/graph-model.md。

// 構造・依存系
CREATE CONSTRAINT system_id IF NOT EXISTS FOR (n:System) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT file_id IF NOT EXISTS FOR (n:File) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT program_id IF NOT EXISTS FOR (n:Program) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT section_id IF NOT EXISTS FOR (n:Section) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT class_id IF NOT EXISTS FOR (n:Class) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT method_id IF NOT EXISTS FOR (n:Method) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT function_id IF NOT EXISTS FOR (n:Function) REQUIRE n.id IS UNIQUE;

// IO 対象系
CREATE CONSTRAINT table_id IF NOT EXISTS FOR (n:Table) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT datafile_id IF NOT EXISTS FOR (n:DataFile) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT externalsystem_id IF NOT EXISTS FOR (n:ExternalSystem) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT messagequeue_id IF NOT EXISTS FOR (n:MessageQueue) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT session_id IF NOT EXISTS FOR (n:Session) REQUIRE n.id IS UNIQUE;

// 処理系
CREATE CONSTRAINT iooperation_id IF NOT EXISTS FOR (n:IOOperation) REQUIRE n.id IS UNIQUE;

// 画面系
CREATE CONSTRAINT screen_id IF NOT EXISTS FOR (n:Screen) REQUIRE n.id IS UNIQUE;
